--AZIZDB
CREATE TABLESPACE aziztbs DATAFILE 
  'D:\ORA\PRASTYO\ORADATA\AZIZDB\aziztbs01.DBF' SIZE 512M REUSE AUTOEXTEND OFF
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

alter database datafile 'D:\ORA\PRASTYO\ORADATA\AZIZDB\AZIZTBS01.DBF' autoextend off;

CREATE DATABASE LINK "vassadw" CONNECT TO VASSADW IDENTIFIED BY "vassadw.123" USING '10.67.18.38:1521/MSPM';

CREATE TABLE azizpw.VASSADWANKR TABLESPACE aziztbs AS SELECT /*+PARALLEL(8)*/ * FROM VASSADW.ANKER@VASSADW;

DROP TABLE azizpw.VASSADWANKR;

ALTER USER AZIZPW DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;

ALTER DATABASE DEFAULT TABLESPACE USERS;

DROP TABLESPACE AZIZTBS INCLUDING CONTENTS AND DATAFILES;

--Kelinci12c
CREATE DATABASE LINK "orawindows" CONNECT TO azizpw IDENTIFIED BY "orekel789" USING '192.168.179.1:1521/azizdb'

CREATE TABLESPACE kelincidata DATAFILE '/oradata/kelinci/kelincidata_01.dbf' SIZE 512M REUSE AUTOEXTEND OFF
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

ALTER USER C##AZIZPW DEFAULT TABLESPACE KELINCIDATA TEMPORARY TABLESPACE TEMP;

CREATE TABLE C##AZIZPW.VASSADWANKR TABLESPACE KELINCIDATA AS SELECT /*+PARALLEL(8)*/ * FROM azizpw.vassadwankr@orawindows

SELECT * FROM VASSADW.ANKER@VASSADW;

SELECT * FROM C##AZIZPW.VASSADWANKR;

SELECT /*+PARALLEL(16)*/ COUNT(1)JML FROM C##AZIZPW.VASSADWANKR;

       JML
----------
  11518651