ALTER SESSION SET NLS_DATE_FORMAT='DD-Mon-RR HH24:MI:SS';

--Analyzed table information
COL OWNER FOR A30;
COL ANALYZED FOR 9999;
SELECT /*+PARALLEL(8)*/ OWNER, SUM(DECODE(NVL(NUM_ROWS,9999), 9999,0,1))Analyzed, SUM(DECODE(NVL(NUM_ROWS,9999), 9999,1,0))Not_Analyzed, COUNT(TABLE_NAME)Total
FROM DBA_TABLES GROUP BY OWNER ORDER BY 1;

--Analyzed table sort by LAST_ANALYZED
COL TBL_NAME FOR A50;
SELECT OWNER||'.'||TABLE_NAME TBL_NAME,LAST_ANALYZED FROM DBA_TABLES WHERE ROWNUM<11 ORDER BY 2 DESC;
