--DATABASE AZIZDB
SELECT * FROM DBA_USERS ORDER BY 1;

SELECT * FROM DBA_TABLESPACES ORDER BY 1;

SELECT * FROM DBA_DATA_FILES ORDER BY 3;

DROP TABLESPACE AZIZTBS INCLUDING CONTENTS;

CREATE BIGFILE TABLESPACE AZIZTBS DATAFILE 'D:\ORA\PRASTYO\ORADATA\AZIZDB\AZIZTBS01.DBF' SIZE 1024M AUTOEXTEND ON;

ALTER DATABASE DEFAULT TABLESPACE AZIZTBS;

SELECT * FROM V$DATABASE;

CREATE USER AZIZPW IDENTIFIED BY orekel DEFAULT TABLESPACE AZIZTBS TEMPORARY TABLESPACE TEMP;

GRANT SYSDBA, RESOURCE, CONNECT TO AZIZPW;