--Check percent CPU of SQL_ID
ALTER SESSION SET NLS_DATE_FORMAT='DD-Mon-RR HH24:MI:SS';
SET LINES 160 PAGES 5000 TIMING ON;
COL NAME FORMAT A26
COL USERNAME FORMAT A15
COL PROGRAM FORMAT A40
COL SESS_CPU_SECS WRA FORMAT 999,999,999.99
COL LAST_CPU_SECS WRA FORMAT 999,999,999.99
COL LOGON_SECS WRA FORMAT 999,999,999
COL PERCENT WRA FORMAT 999.99
SELECT SESS_CPU.SID, SESS_CPU.SERIAL#, NVL(sess_cpu.username, 'Oracle Process') USERNAME, SESS_CPU.STATUS, SESS_CPU.LOGON_TIME,
ROUND((SYSDATE-SESS_CPU.LOGON_TIME)*1440*60) LOGON_SECS, SESS_CPU.VALUE/100 SESS_CPU_SECS, (SESS_CPU.VALUE-CALL_CPU.VALUE)/100 LAST_CPU_SECS,
ROUND((SESS_CPU.VALUE/100)/ROUND((SYSDATE-SESS_CPU.LOGON_TIME)*1440*60)*100,2) PERCENT, SESS_CPU.SQL_ID
FROM
(
  SELECT SE.SQL_ID, SS.STATISTIC#, SE.SID, SE.SERIAL#, SE.USERNAME, SE.STATUS, SE.PROGRAM, SE.LOGON_TIME, SN.NAME, SS.VALUE
  FROM V$SESSION SE, V$SESSTAT SS, V$STATNAME SN
  WHERE SE.SID=SS.SID AND SN.STATISTIC#=SS.STATISTIC# AND SN.NAME IN ('CPU used by this session')
) SESS_CPU,
(
  SELECT SS.STATISTIC#,SE.SID,SS.VALUE,VALUE/100 SECONDS
  FROM V$SESSION SE, V$SESSTAT SS, V$STATNAME SN
  WHERE SE.SID=SS.SID
  AND SN.STATISTIC#=SS.STATISTIC#
  AND SN.NAME IN ('CPU used when call started')
) CALL_CPU
WHERE SESS_CPU.SID=CALL_CPU.SID ORDER BY SESS_CPU_SECS DESC;

--Check CPU usage seconds
SELECT S.USERNAME, T.SID||','||S.SERIAL# SIDSERIAL, SUM(VALUE/100) CPU_USAGE_SECONDS
FROM V$SESSION S, V$SESSTAT T, V$STATNAME N
WHERE
T.STATISTIC#=N.STATISTIC#
AND NAME LIKE '%CPU used by this session%'
AND T.SID=S.SID
AND S.STATUS='ACTIVE'
AND S.USERNAME IS NOT NULL
GROUP BY USERNAME,T.SID||','||S.SERIAL#
ORDER BY 3 DESC;