--Datafile information
COL FILE_NAME FOR A50;
COL TBS FOR A20;
COL OL FOR A10;
SELECT /*+PARALLEL(8)*/
  X.TABLESPACE_NAME TBS, X.FILE_NAME, ROUND(X.BYTES/1024/1024/1024, 2)SIZE_GB, Y.FREE_GB, ROUND(MAXBYTES/1024/1024/1024, 2)MAX_GB, X.STATUS, X.AUTOEXTENSIBLE AUEXT,
  INCREMENT_BY INCR, ONLINE_STATUS OL
FROM
  DBA_DATA_FILES X
JOIN
  (SELECT FILE_ID, ROUND((SUM(BYTES))/1024/1024/1024, 2) FREE_GB FROM DBA_FREE_SPACE Y GROUP BY FILE_ID) Y
ON X.FILE_ID=Y.FILE_ID ORDER BY 1, 2;


SET LINES 200 PAGES 5000;
COL FILE_NAME FORMAT A60;
COL TBS FORMAT A20;
SELECT /*+PARALLEL(8)*/X.TABLESPACE_NAME TBS, X.FILE_NAME, ROUND((X.BYTES/1024/1024/1024), 2)SIZE_GB, Y.FREE_GB,
ROUND((MAXBYTES/1024/1024/1024), 2)MAX_GB, X.STATUS, X.AUTOEXTENSIBLE AUEXT, INCREMENT_BY INCR, ONLINE_STATUS OL
FROM DBA_DATA_FILES X JOIN (SELECT FILE_ID, ROUND((SUM(BYTES))/1024/1024/1024, 2) FREE_GB FROM DBA_FREE_SPACE Y GROUP BY FILE_ID) Y
ON X.FILE_ID=Y.FILE_ID WHERE TABLESPACE_NAME='&TBS' ORDER BY 1, 2; 

SET LINES 200 PAGES 5000;
COL FILE_NAME FORMAT A60;
COL TBS FORMAT A20;
SELECT /*+PARALLEL(8)*/X.TABLESPACE_NAME TBS, X.FILE_NAME, ROUND((X.BYTES/1024/1024/1024), 2)SIZE_GB, Y.FREE_GB, ROUND((MAXBYTES/1024/1024/1024), 2)MAX_GB,
X.STATUS, X.AUTOEXTENSIBLE AUEXT, INCREMENT_BY INCR, ONLINE_STATUS OL
FROM DBA_DATA_FILES X JOIN (SELECT FILE_ID, ROUND((SUM(BYTES))/1024/1024/1024, 2) FREE_GB FROM DBA_FREE_SPACE Y GROUP BY FILE_ID) Y
ON X.FILE_ID=Y.FILE_ID ORDER BY 1, 2; 

SELECT /*+PARALLEL(4)*/ FILE_NAME, TABLESPACE_NAME TBS, ROUND((BYTES/1024/1024/1024), 2)SIZE_GB, STATUS, AUTOEXTENSIBLE AUEXT, ROUND((MAXBYTES/1024/1024/1024), 2)MAX_GB, INCREMENT_BY INCR, ONLINE_STATUS OL FROM DBA_DATA_FILES WHERE TABLESPACE_NAME='&TBS' ORDER BY 1;

SELECT TABLESPACE_NAME, FILE_NAME, ROUND(BYTES/1024/1024,2)SIZE_MB FROM DBA_TEMP_FILES;

SELECT TABLESPACE_NAME, FILE_NAME, ROUND(BYTES/1024/1024,2)SIZE_MB FROM DBA_DATA_FILES WHERE TABLESPACE_NAME='&TBS';

ALTER TABLESPACE TEMP ADD TEMPFILE '/oradata/kelinci/temp02.dbf' SIZE 1G;

CREATE TABLESPACE DIGODA DATAFILE 'D:\ORA\PRASTYO\ORADATA\AZIZDB\DIGODA01.DBF' SIZE 128M;
CREATE TABLESPACE DIPUKUL DATAFILE 'D:\ORA\PRASTYO\ORADATA\AZIZDB\DIPUKUL01.DBF' SIZE 256M;

SELECT FILE_NAME,TABLESPACE_NAME,ROUND(BYTES/1024/1024/1024,2)SIZE_GB,STATUS FROM DBA_TEMP_FILES ORDER BY 1;

ALTER DATABASE TEMPFILE 'D:\APP\ADMINISTRATOR\ORADATA\COLLCARD\TEMP03.DBF' DROP INCLUDING DATAFILES;