SQL> SET LONG 100000;
SQL> SELECT DBMS_METADATA.GET_DDL('TABLE','DEPT','SCOTT')SCOTTDEPT FROM DUAL;

SCOTTDEPT
--------------------------------------------------------------------------------

  CREATE TABLE "SCOTT"."DEPT"
   (    "DEPTNO" NUMBER(2,0),
        "DNAME" VARCHAR2(14),
        "LOC" VARCHAR2(13),
         CONSTRAINT "PK_DEPT" PRIMARY KEY ("DEPTNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"


Elapsed: 00:00:00.72
SQL>

SET LINES 160 PAGES 5000 TIMING ON LONG 10000;

SELECT DBMS_METADATA.GET_DDL('TABLE', '&tblNAME', '&Owner') FROM DUAL;

SELECT 'SELECT DBMS_METADATA.GET_DDL(''TABLE'', '''||SEGMENT_NAME||''', '''||OWNER||''') FROM DUAL;' PERINTAH
FROM APPS.OBJ_ARCHIVE0412 WHERE SEGMENT_TYPE='TABLE';

SELECT DBMS_METADATA.GET_DDL('INDEX', '&idxNAME', '&Owner') FROM DUAL;

SELECT 'SELECT DBMS_METADATA.GET_DDL(''INDEX'', '''||SEGMENT_NAME||''', '''||OWNER||''') FROM DUAL;' PERINTAH
FROM APPS.OBJ_ARCHIVE0412 WHERE SEGMENT_TYPE='INDEX';