--Snap ID for highest dbtime
SET LINES 150 PAGES 5000 TIMING ON;
COL BEGIN_INTERVAL_TIME FOR A30;
COL END_INTERVAL_TIME FOR A30;
SELECT /*+ PARALLEL(8)*/ * FROM
(
  SELECT A.SNAP_ID ASNAPID, C.SNAP_ID CSNAPID, BEGIN_INTERVAL_TIME, END_INTERVAL_TIME, ROUND(TO_NUMBER((C.VALUE-A.VALUE)/1000000/60), 2) DBTIME
  FROM DBA_HIST_SYS_TIME_MODEL A, DBA_HIST_SNAPSHOT B, DBA_HIST_SYS_TIME_MODEL C WHERE A.SNAP_ID=B.SNAP_ID
  AND C.SNAP_ID=A.SNAP_ID+1 AND A.STAT_NAME=C.STAT_NAME AND UPPER(A.STAT_NAME) LIKE '%DB TIME%'
  AND TO_CHAR(B.BEGIN_INTERVAL_TIME,'DD-MM-YYYY')>'&dari' AND TO_CHAR(B.END_INTERVAL_TIME,'DD-MM-YYYY')<='&sampai'
  --AND B.BEGIN_INTERVAL_TIME > SYSDATE-14 AND B.END_INTERVAL_TIME <= SYSDATE
  ORDER BY TO_NUMBER((C.VALUE-A.VALUE)/1000000/60) DESC
) WHERE ROWNUM=1/*Checking dbtime for AWR, version 1.2*/;
