SET LINESIZE 200 PAGESIZE 5000;
SELECT USERNAME, SID, SERIAL#, PROGRAM FROM V$SESSION WHERE USERNAME IS NOT NULL ORDER BY LOGON_TIME;

EXPLAIN PLAN FOR query_statement;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(SQL_ID=>'gr8j48fxfddkt', FORMAT=>'+ALLSTATS'));

SELECT t.*
FROM v$sql s, table(DBMS_XPLAN.DISPLAY_CURSOR(s.sql_id, s.child_number)) t WHERE 
sql_text LIKE '%TOTO%';

OWNER
INDEX_NAME
INDEX_TYPE
TABLE_OWNER
TABLE_NAME
TABLE_TYPE
UNIQUENESS
COMPRESSION

SELECT /*+PARALLEL(4)*/ OWNER||'.'||INDEX_NAME IDX, TABLE_OWNER||'.'||TABLE_NAME TBL, LOGGING, STATUS FROM DBA_INDEXES
WHERE TABLE_OWNER||'.'||TABLE_NAME='MANDIRIMAIN.CS_CASE_DETAILS';

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(SQL_ID=>'9w1ysschbzxbu'));