CONN / AS SYSDBA
GRANT CREATE ANY SQL PROFILE TO APPS;
GRANT ALTER ANY SQL PROFILE TO APPS;
GRANT DROP ANY SQL PROFILE TO APPS;
GRANT ADMINISTER ANY SQL TUNING SET TO APPS;
GRANT ADVISOR TO APPS;
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO APPS;
CONN APPS/APPS;
SHO USER;