SET LINES 200 PAGES 5000;
COL OBJNAME FORMAT A60;
SELECT COUNT(1)INV_OBJ FROM DBA_OBJECTS WHERE STATUS = 'INVALID';
SELECT /*+PARALLEL(8)*/OWNER||'.'||OBJECT_NAME OBJNAME, OBJECT_TYPE OBJTYPE FROM DBA_OBJECTS WHERE STATUS='INVALID' ORDER BY 1;
