SELECT first_name, last_name, salary FROM employees WHERE salary BETWEEN 5000 AND 6000 order by 3;
SELECT last_name, first_name, department_id FROM employees e WHERE EXISTS (select 1 FROM departments d WHERE d.department_id = e.department_id and d.department_name = 'Administration');
SELECT username, sid, serial#, program FROM v$session where username is not null order by logon_time;
SELECT empno "Enumber", ename "EmpName" FROM emp WHERE deptno = 10 AND "Enumber" = 7782 ORDER BY "Enumber";
SELECT country_name, region_id, CASE region_id WHEN 1 THEN 'Europe' WHEN 2 THEN 'America' WHEN 3 THEN 'Asia' ELSE 'Other' END Continent FROM countries;
SELECT first_name, TO_CHAR(hire_date,'Day, DD-Mon-YYYY')hiredate FROM employees WHERE UPPER(first_name) LIKE 'AL%' ORDER BY SOUNDEX(first_name);
SELECT first_name, salary, commission_pct, salary + (salary * commission_pct) compensation FROM employees WHERE first_name LIKE 'T%';
SELECT file_name, SUBSTR(file_name, INSTR(file_name,'/', -1,1)+1) name FROM dba_data_files;
SELECT DISTINCT SUBSTR(file_name, 1, INSTR(file_name,'/', 1,2)-1) fs_name FROM dba_data_files;
SELECT last_name, TRANSLATE(last_name, 'aeiou', '*#$') no_vowel FROM employees WHERE last_name like 'S%';
SELECT first_name, salary, WIDTH_BUCKET(salary, 2500, 11000, 10) hist FROM employees WHERE first_name like 'J%' order by 2;
SELECT TO_DATE('29-02-2008', 'DD-MM-YYYY')BULAN, ADD_MONTHS(TO_DATE('29-02-2008', 'DD-MM-YYYY'), +1)BERIKUT FROM DUAL;
SELECT ROUND(MONTHS_BETWEEN(SYSDATE, TO_DATE('20-09-1991', 'DD-MM-YYYY'))/12, 2)||' Tahun'USIA FROM DUAL;
SELECT SYSDATE, TO_CHAR(SYSDATE,'Mmspth') Month, TO_CHAR(SYSDATE,'DDth') Day, TO_CHAR(SYSDATE,'Yyyysp') Year FROM dual;
SELECT TO_CHAR(-1234.56,'L099G999D99MI', 'NLS_NUMERIC_CHARACTERS='',.''NLS_CURRENCY=''Rp''NLS_ISO_CURRENCY=''Indonesia''') Balance FROM dual;
alter session set nls_data_format='DD-MM-YYYY';
select TO_DATE('01-01-08','DD-MM-RR')tanggal from dual;
SET VERIFY OFF;
SELECT GREATEST('01-ARP-08','30-DEC-01','12-SEP-09') FROM dual;
SELECT last_name, salary, GREATEST(LEAST(salary*0.15, 500), 400) bonus FROM employees WHERE department_id IN (30, 10) ORDER BY last_name;
SELECT last_name, NVL2(salary, salary, 0) N1, NVL(salary,0) N2 FROM employees;
SELECT RTRIM(last_name, SUBSTR(last_name, LENGTH(last_name)-1)) || 'XX' new_col FROM employees;
SELECT REPLACE(last_name, SUBSTR(last_name, LENGTH(last_name)-1), 'XX') new_col FROM employees;
SELECT REPLACE(SUBSTR(last_name, LENGTH(last_name)-1), 'XX') new_col FROM employees;
SELECT CONCAT(SUBSTR(last_name, 1,LENGTH(last_name)-2), 'XX') new_col FROM employees;
SELECT ADD_MONTHS('28-FEB-09', -12) from dual;
SELECT TO_DATE('30-SEP-07','DD-MM-YYYY') from dual;
SELECT TO_DATE('30-SEP-07','DD-MON-RRRR') from dual;
SELECT COALESCE(NULL,'Oracle ','Certified') FROM dual;
SELECT SUM(bytes)/1048576 size_mb FROM dba_segments;
SELECT department_id, COUNT(*) emp_count, AVG(salary) mean, DENSE_RANK(10000) WITHIN GROUP (ORDER BY salary DESC) dense_rank_10K FROM hr.employees GROUP BY department_id;
SELECT department_id, MIN(hire_date) earliest, MAX(hire_date) latest, COUNT(salary) KEEP (DENSE_RANK FIRST ORDER BY hire_date) FIRST, COUNT(salary) KEEP (DENSE_RANK LAST ORDER BY hire_date) LAST FROM hr.employees GROUP BY department_id;
SELECT DEPARTMENT_ID DID, COUNT(*) emp_count, AVG(salary) mean, PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY salary DESC) median, PERCENT_RANK(10000) WITHIN GROUP (ORDER BY salary DESC)*100 pct_rank_10K, CUME_DIST(10000) WITHIN GROUP (ORDER BY salary DESC)*100 cume_dist_10K FROM hr.employees GROUP BY department_id;
select commission_pct, count(1)jml from employees group by cube(commission_pct);
select commission_pct, count(1)jml from employees group by rollup(commission_pct);
SELECT SUM (decode (name,'sorts (memory)',value,0))mem from v$sysstat;
SELECT deptno, GREATEST(COUNT(DISTINCT job), COUNT(DISTINCT mgr)) cnt, COUNT(DISTINCT job) jobs, COUNT(DISTINCT mgr) mgrs FROM scott.emp GROUP BY deptno;
SELECT department_id, COUNT(*) FROM employees HAVING COUNT(*) > 10 GROUP BY department_id;
SELECT department_id, COUNT(*) FROM employees WHERE COUNT(*) > 10 GROUP BY department_id/*ga bisa*/;
SELECT MAX(COUNT(*)) FROM employees GROUP BY job_id, department_id;
SELECT COUNT(DISTINCT last_name), MAX(DISTINCT salary) FROM azizpw.employees;
SELECT COUNT(ALL last_name), MAX(ALL salary) FROM azizpw.employees;
select substr(first_name, 1,1) fn, SUM(salary) FROM employees GROUP BY first_name;
select substr(first_name, 1,1) fn, SUM(salary) FROM employees GROUP BY substr(first_name, 1,1);
sELECT department_id, AVG(salary) avg_sal FROM employees GROUP BY department_id HAVING TRUNC(department_id) > 50;
SELECT JOB_id FROM EMPLOYEEs WHERE department_id= 30 INTERSECT SELECT JOB_id FROM EMPLOYEEs WHERE DEPartment_id = 20;
SELECT tablespace_name, round(SUM(bytes)/1048576, 2) UsedMB FROM dba_data_files group by tablespace_name order by 2 desc;
SELECT tablespace_name, round(SUM(bytes)/1048576, 2) UsedMB, 0 FreeMB FROM dba_data_files GROUP BY tablespace_name UNION ALL SELECT tablespace_name, round(SUM(bytes)/1048576, 2) UsedMB, 0 FreeMB FROM dba_temp_files GROUP BY tablespace_name UNION ALL SELECT tablespace_name, 0 UsedMB, round(SUM(bytes)/1048576, 2) FreeMB FROM dba_free_space GROUP BY tablespace_name;
