SET LINES 150 PAGES 5000 TIMING ON ECHO ON;
COL FILE_NAME FOR A55;
SELECT A.TABLESPACE_NAME, A.FILE_NAME, A.BYTES C3, B.FREE_BYTES
FROM DBA_TEMP_FILES A
JOIN (SELECT FILE_ID, SUM(BYTES) FREE_BYTES FROM DBA_FREE_SPACE B GROUP BY FILE_ID) B
ON A.FILE_ID=B.FILE_ID ORDER BY A.TABLESPACE_NAME;

SELECT
 A.USERNAME, A.STATUS, A.SCHEMANAME, A.OSUSER, A.MACHINE, A.PROGRAM, A.LOGON_TIME, A.EVENT, 'ALTER SYSTEM KILL SESSION '''||A.SID||','||A.SERIAL#||''' IMMEDIATE;' COMMAND
FROM V$SESSION A, V$SORT_USAGE B, V$PROCESS C, V$PARAMETER D
WHERE
  D.NAME = 'db_block_size' AND A.SADDR = B.SESSION_ADDR AND A.PADDR = C.ADDR AND B.TABLESPACE='TEMP'
ORDER BY
  B.TABLESPACE, B.SEGFILE#, B.SEGBLK#, B.BLOCKS;​

--Tempfile information
SET LINES 150 PAGES 5000 TIMING ON;
COL TABLESPACE_NAME FOR A20;
COL FILE_NAME FOR A55;
COL OL FOR A10;
SELECT /*+ PARALLEL(8)*/
  TABLESPACE_NAME,FILE_ID,FILE_NAME,ROUND(VT.BYTES/1024/1024/1024,2)SIZE_GB,ROUND(MAXBYTES/1024/1024/1024,2)MAX_GB,AUTOEXTENSIBLE,DTF.STATUS,VT.ENABLED
FROM DBA_TEMP_FILES DTF
JOIN V$TEMPFILE VT ON VT.NAME=DTF.FILE_NAME
ORDER BY 1,2;

ALTER DATABASE TEMPFILE '/temp/wmos/wmos_temp03.dbf' DROP INCLUDING DATAFILES;

ALTER TABLESPACE TEMP ADD TEMPFILE '/oradata/ayam/temp01.dbf' SIZE 128M AUTOEXTEND ON NEXT 10M MAXSIZE 5G;

ALTER TABLESPACE TEMP DROP TEMPFILE '/oradata/ayam/temp01.dbf';